
const ADD_POST = 'ADD_POST';
const EDIT_POST = 'EDIT_POST';
const GET_POST_BY_ID = 'GET_POST_BY_ID';
const DELETE_POST = 'DELETE_POST';
const REST_POST_OBJECT = 'REST_POST_OBJECT';


export const PostActionsType = {
    ADD_POST, DELETE_POST, EDIT_POST, GET_POST_BY_ID, REST_POST_OBJECT
}