const ADD_COMMENT = 'ADD_COMMENT';
const EDIT_COMMENT = 'EDIT_COMMENT';
const GET_COMMENT_BY_ID = 'GET_COMMENT_BY_ID';
const DELETE_COMMENT = 'DELETE_COMMENT';
const REST_COMMENT_OBJECT = 'REST_COMMENT_OBJECT';


export const commentActionsType = {
    ADD_COMMENT, DELETE_COMMENT, EDIT_COMMENT, GET_COMMENT_BY_ID, REST_COMMENT_OBJECT
}